### ISSUE TITLE
Unhandled exception: ProcessException: The specified file cannot be found.

### ISSUE THREAD

**Issue by SergeyGalaxyOrsik** [Mobile-Innowise-Group/DevPilot#11]
All the installation conditions were met, however, the following error appears when creating the project:

```
Unhandled exception:
ProcessException: Не удается найти указанный файл.

  Command: flutter create --no-pub --org com.example --project-name test C:\Users\User/test
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/dev_pilot-1.0.8/bin/dev_pilot.dart:167:42)
<asynchronous suspension>
```

**Comment by kemalinnowise** [comment]
@SergeyGalaxyOrsik  The Problem seems to refer to the bash. In a main file we use [Process.run ](https://api.dart.dev/stable/3.0.5/dart-io/Process/run.html) from dart:io to access bash commands however I guess u may use power shell therefore conflict may occur. Please try install git bash and set proper PATH. We tried run dev_pilot in our windows machine and it does work correctly

**Comment by SergeyGalaxyOrsik** [comment]
@kemalinnowise I tried install git bash and set PATH, however it's doesn't work on my PC
![Без имени](https://github.com/Mobile-Innowise-Group/DevPilot/assets/93079311/11fe0bc9-6fc0-4173-9bb7-7a1ee79130d5)

**Comment by SergeyGalaxyOrsik** [comment]
I have same problem

**Comment by kemalinnowise** [comment]
@SergeyGalaxyOrsik  I've update main file and add ability work with power shell as well. I just upload new version please download v1.0.9 and try again

**Comment by SergeyGalaxyOrsik** [comment]
@kemalinnowise  Now the application is being created, but the following error appears:
```
Unhandled exception:
ProcessException: Не удается найти указанный файл.

  Command: flutter clean
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      ScriptService.flutterClean (package:dev_pilot/src/services/script_service.dart:15:54)
#5      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/dev_pilot-1.0.9/bin/dev_pilot.dart:219:27)
<asynchronous suspension>
```

**Comment by kemalinnowise** [comment]
@SergeyGalaxyOrsik  Please try one more time. The version 1.0.10 Should resolve the issue.

**Comment by SergeyGalaxyOrsik** [comment]
O, thanks you very much! You really resolved this problem!

But I have this error, I don't now maybe it is my mistake 
![2023-06-22_22-03-03](https://github.com/Mobile-Innowise-Group/DevPilot/assets/93079311/609f5cc1-b9a1-40d9-9d42-a913027b9786)

**Comment by kemalinnowise** [comment]
> O, thanks you very much! You really resolved this problem!
> 
> But I have this error, I don't now maybe it is my mistake ![2023-06-22_22-03-03](https://user-images.githubusercontent.com/93079311/248032074-609f5cc1-b9a1-40d9-9d42-a913027b9786.png)

As all the other scripts for pub get & flutter clean run successfully I assume that the error occurs due to some connection errors. However this one is not crucial so u may run pub get manually in the navigation module of your project!
I'll close issue as Problem with scripts was resolved

**Comment by kemalinnowise** [comment]
Resolved according screenshots provided by issuer
